import React, { useEffect, useRef, useState } from 'react';
import { Camera, CameraOff, Mic, MicOff, PhoneOff } from 'lucide-react';
import { api } from '../../api.js';
import { Orb } from '../../ui.jsx';

const ICE_SERVERS = (() => {
  const servers = [{ urls: ['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302'] }];
  const turn = String(import.meta.env.VITE_TURN_URL || '').split(',').map(v=>v.trim()).filter(Boolean);
  if (turn.length) servers.push({ urls:turn, username:import.meta.env.VITE_TURN_USERNAME || '', credential:import.meta.env.VITE_TURN_CREDENTIAL || '' });
  return servers;
})();

/** WebRTC 1:1; a API troca apenas signaling autenticado, nunca o áudio/vídeo. */
export function CallOverlay({ call, caller, person, onClosed, ping }) {
  const [phase,setPhase]=useState(caller?'A chamar…':'A ligar…'), [muted,setMuted]=useState(false), [cameraOff,setCameraOff]=useState(false), [remoteReady,setRemoteReady]=useState(false);
  const localVideo=useRef(null),remoteMedia=useRef(null),pcRef=useRef(null),streamRef=useRef(null),pollRef=useRef(null),lastSignalRef=useRef(0),answeredOfferRef=useRef(false),closedRef=useRef(false),pendingIceRef=useRef([]);

  const cleanup=async({notify=false}={})=>{if(closedRef.current)return;closedRef.current=true;clearInterval(pollRef.current);pollRef.current=null;try{pcRef.current?.close()}catch{}pcRef.current=null;streamRef.current?.getTracks?.().forEach(t=>t.stop());streamRef.current=null;if(notify)await api.calls.end(call.id).catch(()=>{});onClosed?.();};
  const flushIce=async()=>{const pc=pcRef.current;if(!pc?.remoteDescription)return;for(const c of pendingIceRef.current.splice(0)){try{await pc.addIceCandidate(new RTCIceCandidate(c))}catch(e){console.debug('[call] ICE rejeitado',e?.message)}}};
  const sendDescription=(kind,d)=>api.calls.signal(call.id,kind,{type:d.type,sdp:d.sdp});
  const handleSignal=async signal=>{const pc=pcRef.current;if(!pc)return;if(signal.kind==='hangup')return cleanup();if(signal.kind==='offer'){if(caller||answeredOfferRef.current)return;answeredOfferRef.current=true;await pc.setRemoteDescription(new RTCSessionDescription(signal.payload));await flushIce();const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await sendDescription('answer',answer);setPhase('A ligar…');return;}if(signal.kind==='answer'){if(!caller||pc.remoteDescription)return;await pc.setRemoteDescription(new RTCSessionDescription(signal.payload));await flushIce();return;}if(signal.kind==='ice'&&signal.payload){if(!pc.remoteDescription){pendingIceRef.current.push(signal.payload);return;}try{await pc.addIceCandidate(new RTCIceCandidate(signal.payload))}catch(e){console.debug('[call] ICE rejeitado',e?.message)}}};
  const startPolling=()=>{clearInterval(pollRef.current);const poll=async()=>{try{const signals=await api.calls.signals(call.id,lastSignalRef.current);for(const signal of signals){lastSignalRef.current=Math.max(lastSignalRef.current,Number(signal.id)||0);await handleSignal(signal)}const current=await api.calls.get(call.id);if(current.status==='declined'){setPhase('Chamada recusada');setTimeout(()=>cleanup(),650)}else if(current.status==='ended')cleanup();else if(current.status==='active'&&!remoteReady)setPhase('A ligar…')}catch(e){if(!closedRef.current)console.debug('[call] polling',e?.message)}};poll();pollRef.current=setInterval(poll,1500);};

  useEffect(()=>{let mounted=true;(async()=>{try{if(!navigator.mediaDevices?.getUserMedia||typeof RTCPeerConnection==='undefined')throw new Error('Este dispositivo/browser não permite chamadas WebRTC.');const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:call.mode==='video'?{facingMode:'user',width:{ideal:1280},height:{ideal:720}}:false});if(!mounted){stream.getTracks().forEach(t=>t.stop());return;}streamRef.current=stream;if(localVideo.current){localVideo.current.srcObject=stream;localVideo.current.play?.().catch(()=>{})}const pc=new RTCPeerConnection({iceServers:ICE_SERVERS});pcRef.current=pc;stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const remote=e.streams?.[0];if(remoteMedia.current&&remote){remoteMedia.current.srcObject=remote;remoteMedia.current.play?.().catch(()=>{})}setRemoteReady(true);setPhase('Em chamada')};pc.onicecandidate=e=>{if(e.candidate)api.calls.signal(call.id,'ice',e.candidate.toJSON?.()||e.candidate).catch(()=>{})};pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected')setPhase('Em chamada');if(pc.connectionState==='disconnected')setPhase('A restabelecer…');if(['failed','closed'].includes(pc.connectionState)&&!closedRef.current)cleanup({notify:true})};startPolling();if(caller){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendDescription('offer',offer)}}catch(e){ping?.(e?.name==='NotAllowedError'?'Permite microfone/câmara para fazer a chamada.':e.message);cleanup({notify:true})}})();return()=>{mounted=false;cleanup()};},[call.id]);

  const toggleMute=()=>{const next=!muted;streamRef.current?.getAudioTracks?.().forEach(t=>{t.enabled=!next});setMuted(next)};
  const toggleCamera=()=>{if(call.mode!=='video')return;const next=!cameraOff;streamRef.current?.getVideoTracks?.().forEach(t=>{t.enabled=!next});setCameraOff(next)};

  return <div role="dialog" aria-label={`${call.mode==='video'?'Videochamada':'Chamada áudio'} com ${person.name}`} style={{position:'fixed',inset:0,zIndex:180,background:'#080711',color:'#fff',display:'grid',overflow:'hidden'}}>
    {call.mode==='video'?<><video ref={remoteMedia} playsInline autoPlay aria-label="Vídeo remoto" style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',background:'#090713'}}/>{!remoteReady&&<div style={{position:'absolute',inset:0,display:'grid',placeItems:'center',background:'radial-gradient(circle at 50% 35%,#342466,#080711 65%)'}}><div style={{textAlign:'center'}}><Orb p={person.palette} avatarUrl={person.avatar_url} s={112}/><div className="d" style={{fontSize:31,marginTop:15,color:'#fff'}}>{person.name}</div><div style={{opacity:.68,marginTop:7}}>{phase}</div></div></div>}<div style={{position:'absolute',top:'calc(16px + env(safe-area-inset-top))',right:14,width:108,height:154,borderRadius:22,overflow:'hidden',border:'1px solid rgba(255,255,255,.3)',background:'#171425',boxShadow:'0 12px 30px rgba(0,0,0,.34)'}}><video ref={localVideo} playsInline autoPlay muted aria-label="O teu vídeo" style={{width:'100%',height:'100%',objectFit:'cover',transform:'scaleX(-1)'}}/></div></>:<div style={{position:'absolute',inset:0,display:'grid',placeItems:'center',background:'radial-gradient(circle at 50% 30%,#47327D,#17102E 46%,#080711 78%)'}}><div style={{textAlign:'center',transform:'translateY(-45px)'}}><div style={{padding:7,borderRadius:'50%',background:'linear-gradient(135deg,#FF6558,#624DFF)',display:'inline-grid'}}><Orb p={person.palette} avatarUrl={person.avatar_url} s={122}/></div><div className="d" style={{fontSize:34,marginTop:19,color:'#fff'}}>{person.name}</div><div style={{opacity:.68,marginTop:8}}>{phase}</div></div><audio ref={remoteMedia} autoPlay/></div>}
    <div style={{position:'absolute',left:0,right:0,bottom:'calc(28px + env(safe-area-inset-bottom))',display:'flex',justifyContent:'center',gap:16,zIndex:3}}><button onClick={toggleMute} aria-label={muted?'Ativar microfone':'Desativar microfone'} style={{width:58,height:58,borderRadius:99,border:0,background:'rgba(255,255,255,.16)',backdropFilter:'blur(13px)',color:'#fff',display:'grid',placeItems:'center'}}>{muted?<MicOff/>:<Mic/>}</button>{call.mode==='video'&&<button onClick={toggleCamera} aria-label={cameraOff?'Ativar câmara':'Desativar câmara'} style={{width:58,height:58,borderRadius:99,border:0,background:'rgba(255,255,255,.16)',backdropFilter:'blur(13px)',color:'#fff',display:'grid',placeItems:'center'}}>{cameraOff?<CameraOff/>:<Camera/>}</button>}<button onClick={()=>cleanup({notify:true})} aria-label="Terminar chamada" style={{width:64,height:64,borderRadius:99,border:0,background:'#FF5149',color:'#fff',display:'grid',placeItems:'center',boxShadow:'0 10px 30px rgba(255,81,73,.34)'}}><PhoneOff size={28}/></button></div>
  </div>;
}
