version: 2
updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    labels:
      - dependencies
