import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const platform = process.argv[2];
if (!['android', 'ios'].includes(platform)) throw new Error('Usage: node configure-native.mjs <android|ios>');

const here = path.dirname(fileURLToPath(import.meta.url));
const mobileRoot = path.resolve(here, '..');
const repoRoot = path.resolve(mobileRoot, '..');
const iconSource = path.join(repoRoot, 'web/public/icon-512.png');
const APP_ID = 'com.crilimcf.lumina';
const APP_NAME = 'Lumina';
const VERSION = process.env.LUMINA_VERSION || '1.0.0';
const BUILD = Number(process.env.LUMINA_BUILD || '1');

async function exists(file) { try { await fs.access(file); return true; } catch { return false; } }
async function read(file) { return fs.readFile(file, 'utf8'); }
async function write(file, value) { await fs.mkdir(path.dirname(file), { recursive:true }); await fs.writeFile(file, value); }

function insertBefore(text, marker, addition) {
  if (text.includes(addition.trim())) return text;
  const index = text.indexOf(marker);
  if (index < 0) throw new Error(`Marker not found: ${marker}`);
  return `${text.slice(0,index)}${addition}${text.slice(index)}`;
}

async function android() {
  const root = path.join(mobileRoot, 'android');
  const manifestPath = path.join(root, 'app/src/main/AndroidManifest.xml');
  if (!await exists(manifestPath)) throw new Error('Android project has not been generated by Capacitor.');

  let manifest = await read(manifestPath);
  const permissions = [
    'android.permission.INTERNET',
    'android.permission.CAMERA',
    'android.permission.RECORD_AUDIO',
    'android.permission.ACCESS_COARSE_LOCATION',
    'android.permission.ACCESS_FINE_LOCATION',
    'android.permission.POST_NOTIFICATIONS',
  ];
  for (const permission of permissions) {
    if (!manifest.includes(`android:name="${permission}"`)) {
      manifest = manifest.replace('<application', `    <uses-permission android:name="${permission}" />\n\n    <application`);
    }
  }
  if (!manifest.includes('android:scheme="lumina"')) {
    const activityEnd = manifest.indexOf('</activity>');
    if (activityEnd < 0) throw new Error('Main Android activity not found.');
    const filter = `            <intent-filter>\n                <action android:name="android.intent.action.VIEW" />\n                <category android:name="android.intent.category.DEFAULT" />\n                <category android:name="android.intent.category.BROWSABLE" />\n                <data android:scheme="lumina" />\n            </intent-filter>\n`;
    manifest = `${manifest.slice(0,activityEnd)}${filter}${manifest.slice(activityEnd)}`;
  }
  await write(manifestPath, manifest);

  const variablesPath = path.join(root, 'variables.gradle');
  if (await exists(variablesPath)) {
    let variables = await read(variablesPath);
    variables = variables.replace(/compileSdkVersion\s*=\s*\d+/, 'compileSdkVersion = 36');
    variables = variables.replace(/targetSdkVersion\s*=\s*\d+/, 'targetSdkVersion = 36');
    await write(variablesPath, variables);
  }

  const appGradleCandidates = [path.join(root, 'app/build.gradle'), path.join(root, 'app/build.gradle.kts')];
  for (const gradlePath of appGradleCandidates) {
    if (!await exists(gradlePath)) continue;
    let gradle = await read(gradlePath);
    gradle = gradle.replace(/versionCode\s*[= ]\s*\d+/, match => match.includes('=') ? `versionCode = ${BUILD}` : `versionCode ${BUILD}`);
    gradle = gradle.replace(/versionName\s*[= ]\s*["'][^"']+["']/, match => match.includes('=') ? `versionName = "${VERSION}"` : `versionName "${VERSION}"`);
    await write(gradlePath, gradle);
  }

  const res = path.join(root, 'app/src/main/res');
  const sizes = { mdpi:48, hdpi:72, xhdpi:96, xxhdpi:144, xxxhdpi:192 };
  for (const [density, size] of Object.entries(sizes)) {
    const dir = path.join(res, `mipmap-${density}`);
    await fs.mkdir(dir, { recursive:true });
    const image = await sharp(iconSource).resize(size, size, { fit:'contain' }).png().toBuffer();
    await fs.writeFile(path.join(dir, 'ic_launcher.png'), image);
    await fs.writeFile(path.join(dir, 'ic_launcher_round.png'), image);
    await fs.writeFile(path.join(dir, 'ic_launcher_foreground.png'), image);
  }
  for (const name of ['ic_launcher.xml', 'ic_launcher_round.xml']) {
    await fs.rm(path.join(res, 'mipmap-anydpi-v26', name), { force:true }).catch(() => {});
  }

  const stringsPath = path.join(res, 'values/strings.xml');
  if (await exists(stringsPath)) {
    let strings = await read(stringsPath);
    strings = strings.replace(/<string name="app_name">[\s\S]*?<\/string>/, `<string name="app_name">${APP_NAME}</string>`);
    strings = strings.replace(/<string name="title_activity_main">[\s\S]*?<\/string>/, `<string name="title_activity_main">${APP_NAME}</string>`);
    strings = strings.replace(/<string name="package_name">[\s\S]*?<\/string>/, `<string name="package_name">${APP_ID}</string>`);
    strings = strings.replace(/<string name="custom_url_scheme">[\s\S]*?<\/string>/, '<string name="custom_url_scheme">lumina</string>');
    await write(stringsPath, strings);
  }

  console.log(`[mobile] Android configured: ${APP_ID} ${VERSION} (${BUILD}), target API 36.`);
}

const iosIcons = [
  ['Icon-App-20x20@1x.png',20,'20x20','1x','ipad'], ['Icon-App-20x20@2x.png',40,'20x20','2x','iphone'],
  ['Icon-App-20x20@3x.png',60,'20x20','3x','iphone'], ['Icon-App-29x29@1x.png',29,'29x29','1x','ipad'],
  ['Icon-App-29x29@2x.png',58,'29x29','2x','iphone'], ['Icon-App-29x29@3x.png',87,'29x29','3x','iphone'],
  ['Icon-App-40x40@1x.png',40,'40x40','1x','ipad'], ['Icon-App-40x40@2x.png',80,'40x40','2x','iphone'],
  ['Icon-App-40x40@3x.png',120,'40x40','3x','iphone'], ['Icon-App-60x60@2x.png',120,'60x60','2x','iphone'],
  ['Icon-App-60x60@3x.png',180,'60x60','3x','iphone'], ['Icon-App-76x76@1x.png',76,'76x76','1x','ipad'],
  ['Icon-App-76x76@2x.png',152,'76x76','2x','ipad'], ['Icon-App-83.5x83.5@2x.png',167,'83.5x83.5','2x','ipad'],
  ['Icon-App-1024x1024@1x.png',1024,'1024x1024','1x','ios-marketing'],
];

async function ios() {
  const root = path.join(mobileRoot, 'ios');
  const plistPath = path.join(root, 'App/App/Info.plist');
  if (!await exists(plistPath)) throw new Error('iOS project has not been generated by Capacitor.');

  let plist = await read(plistPath);
  const stringKeys = {
    NSCameraUsageDescription:'A Lumina usa a câmara quando escolhes tirar uma fotografia, gravar vídeo ou iniciar uma videochamada.',
    NSMicrophoneUsageDescription:'A Lumina usa o microfone em chamadas, vídeos e transmissões iniciadas por ti.',
    NSPhotoLibraryUsageDescription:'A Lumina acede às fotografias e vídeos apenas quando escolhes conteúdo para partilhar.',
    NSPhotoLibraryAddUsageDescription:'A Lumina pode guardar uma fotografia no dispositivo quando pedes explicitamente para a guardar.',
    NSLocationWhenInUseUsageDescription:'A localização é usada apenas quando pedes experiências locais no Lumina One.',
  };
  for (const [key, value] of Object.entries(stringKeys)) {
    if (!plist.includes(`<key>${key}</key>`)) plist = insertBefore(plist, '</dict>', `\t<key>${key}</key>\n\t<string>${value}</string>\n`);
  }
  if (!plist.includes('<string>lumina</string>')) {
    plist = insertBefore(plist, '</dict>', `\t<key>CFBundleURLTypes</key>\n\t<array>\n\t\t<dict>\n\t\t\t<key>CFBundleURLName</key>\n\t\t\t<string>${APP_ID}</string>\n\t\t\t<key>CFBundleURLSchemes</key>\n\t\t\t<array><string>lumina</string></array>\n\t\t</dict>\n\t</array>\n`);
  }
  if (!plist.includes('<key>UIBackgroundModes</key>')) {
    plist = insertBefore(plist, '</dict>', '\t<key>UIBackgroundModes</key>\n\t<array><string>remote-notification</string></array>\n');
  }
  await write(plistPath, plist);

  const entitlementsPath = path.join(root, 'App/App/App.entitlements');
  await write(entitlementsPath, `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>aps-environment</key>\n\t<string>production</string>\n</dict>\n</plist>\n`);

  const projectPath = path.join(root, 'App/App.xcodeproj/project.pbxproj');
  if (await exists(projectPath)) {
    let project = await read(projectPath);
    project = project.replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${VERSION};`);
    project = project.replace(/CURRENT_PROJECT_VERSION = [^;]+;/g, `CURRENT_PROJECT_VERSION = ${BUILD};`);
    if (!project.includes('CODE_SIGN_ENTITLEMENTS = App/App.entitlements;')) {
      project = project.replace(/CODE_SIGN_STYLE = Automatic;/g, 'CODE_SIGN_ENTITLEMENTS = App/App.entitlements;\n\t\t\t\tCODE_SIGN_STYLE = Automatic;');
    }
    await write(projectPath, project);
  }

  const appIcon = path.join(root, 'App/App/Assets.xcassets/AppIcon.appiconset');
  await fs.mkdir(appIcon, { recursive:true });
  const images = [];
  for (const [filename, pixels, size, scale, idiom] of iosIcons) {
    await sharp(iconSource).resize(pixels, pixels, { fit:'cover' }).png().toFile(path.join(appIcon, filename));
    images.push({ filename, idiom, scale, size });
  }
  await write(path.join(appIcon, 'Contents.json'), JSON.stringify({ images, info:{ author:'xcode', version:1 } }, null, 2));

  console.log(`[mobile] iOS configured: ${APP_ID} ${VERSION} (${BUILD}) with native permissions, push entitlement and deep link.`);
}

if (platform === 'android') await android();
else await ios();
